"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.routes = void 0;
const express_1 = __importDefault(require("express"));
const authRoute_1 = require("./authRoute");
const colorRoute_1 = require("./colorRoute");
const lengthRoute_1 = require("./lengthRoute");
const sizeRoute_1 = require("./sizeRoute");
const productTypeRoute_1 = require("./productTypeRoute");
const productCategoryRoute_1 = require("./productCategoryRoute");
const collectionTYpeRoute_1 = require("./collectionTYpeRoute");
const productRoute_1 = require("./productRoute");
const productDetailRoute_1 = require("./productDetailRoute");
const razerpayRouter_1 = require("./razerpayRouter");
const customerRoute_1 = require("./customerRoute");
const customerAddRoute_1 = require("./customerAddRoute");
const orderRoute_1 = require("./orderRoute");
const guestCartRoute_1 = require("./guestCartRoute");
exports.routes = express_1.default.Router();
exports.routes.use(authRoute_1.authroute);
exports.routes.use(colorRoute_1.colorroute);
exports.routes.use(lengthRoute_1.lengthroute);
exports.routes.use(sizeRoute_1.sizeroute);
exports.routes.use(productTypeRoute_1.producttyperoute);
exports.routes.use(productCategoryRoute_1.productcategoryroute);
exports.routes.use(collectionTYpeRoute_1.collectiontyperoute);
exports.routes.use(productRoute_1.productroute);
exports.routes.use(productDetailRoute_1.productDetailroute);
exports.routes.use(razerpayRouter_1.razerpayroute);
exports.routes.use(customerRoute_1.customerroute);
exports.routes.use(customerAddRoute_1.customeraddressroute);
exports.routes.use(orderRoute_1.orderroute);
exports.routes.use(guestCartRoute_1.guestCartroute);
